name: deploy app with maven and tomcat

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package  --file pom.xml
    - name: deploy Ecomm-app to TomcatServer
      run: curl -v -u admin:admin -T /home/runner/work/Ebusiness/Ebusiness/target/Ecomm.war 'http://15.206.89.3:8080/manager/text/deploy?path=/Ecomm.war'
      
    
